
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    apellido character varying(50) COLLATE pg_catalog."default",
    dni character varying(50) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.detalle_pedido
(
    id_detalle serial NOT NULL,
    id_pedido integer,
    id_producto integer,
    cantidad integer,
    subtotal numeric(10, 2),
    CONSTRAINT detalle_pedido_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    id_pedido integer,
    metodo character varying(50) COLLATE pg_catalog."default",
    monto numeric(10, 2),
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id_pedido serial NOT NULL,
    id_vendedor integer,
    id_cliente integer,
    fecha timestamp without time zone,
    estado character varying(20) COLLATE pg_catalog."default",
    total numeric(10, 2),
    CONSTRAINT pedido_pkey PRIMARY KEY (id_pedido)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id_producto serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    precio numeric(10, 2),
    stock integer,
    CONSTRAINT producto_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.vendedor
(
    id_vendedor serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default",
    apellido character varying(50) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default",
    correo character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT vendedor_pkey PRIMARY KEY (id_vendedor)
);

ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT detalle_pedido_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detalle_pedido
    ADD CONSTRAINT detalle_pedido_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT pago_id_pedido_fkey FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id_pedido) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pedido
    ADD CONSTRAINT pedido_id_vendedor_fkey FOREIGN KEY (id_vendedor)
    REFERENCES public.vendedor (id_vendedor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;